/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MusicBot;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    /*
    @Test public void testAppHasAGreeting() {
        MusicBot classUnderTest = new MusicBot();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
    */

}
